### ISSUE TITLE
Would you ever publish library to work with ESP32?

### ISSUE THREAD

**Issue by happytm** [InqOnThat/InqPortal#1]
Nice Library. I want to use this library with ESP32.

Thanks.

**Comment by InqOnThat** [comment]
I've had several people ask about porting to ESP32 and I'd like it for my own projects.  However, it uses the low level Espressif routines under the NonOS version of their infrastructure.  As they don't provide that same NonOS for ESP32, it is not a simple port.  Apologies also for the slow response.  This was my first GitHub publishing and I expected to be notified by email and text that someone had submitted an Issue.    - Inq

**Comment by unrealex** [comment]
Has happytm said. Nice library. I also would like an ESP32 port.
Thank you for all the effort to make the library and publish in github.
